version: '3'

services:
  emoji:
    build: .
    container_name: emoji
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:${PORT}"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - emoji-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - emoji-network

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "54323:${DB_PORT}"
    networks:
      - emoji-network

networks:
  emoji-network:
    driver: "bridge"
